
version: "0.5"
is_strict: true
processes:
  gosvc:
    namespace: "Classic"
    working_dir: "./gosvc"
    environment:
      - "AAA=bbb"
    command: go run main.go
    availability:
      restart: "always"
    depends_on:
      redis:
        condition: process_started
    liveness_probe:
      exec:
        command: "nc -z localhost 8080"
      initial_delay_seconds: 5
      period_seconds: 2
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/"
        port: 8080
      initial_delay_seconds: 5
      period_seconds: 2
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
  postgresql:
    disabled: true
